bank/urls.py
from django.conf.urls import url
from . import views

app_name = 'bank' #app name for namespace

urlpatterns = [
    url(r'^$', views.index, name='main'),   # main page
    url(r'^login/$', views.login_form, name='login_form'),  # login page
    url(r'^login/login$', views.login_action, name='login'),    # login action
    url(r'^logout/$', views.logout_action, name='logout'),  # logout action
    url(r'^menu/$', views.menu, name="menu"),   # menu
    url(r'^menu/balance/$', views.balance, name="balance"), # balance
    url(r'^menu/transfer/$', views.transfer_form, name="transfer_form"),# transfer page
    url(r'^menu/transfer/transfer/$', views.transfer, name='transfer'), # transfer action
]

internet_banking/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),   # admin url
    url(r'^', include('bank.urls')),    # include the url file in bank folders
]

bank/models.py
from django.db import models


# Create your models here.
class Account(models.Model):
    user = models.OneToOneField('auth.User')   #link this field with Django User.
    GENDER = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER) # gender field
    balance = models.IntegerField(default=0)    # balance field

    def __str__(self):
        return self.user.get_full_name()    # return full name in admin site.

bank/views.py
from django.shortcuts import render, redirect  # importing modules for render page and redirect page
from django.contrib.auth import authenticate, login, logout  # importing modules for authenticate, login and logout
from django.contrib.auth.decorators import \
    login_required  # importing modules for redirecting to login page if entering page that needs login
from django.contrib.auth.models import User  # importing User objects that already exist in Django
from django.contrib import messages  # importing message for alert if there's error
from django.core.exceptions import ObjectDoesNotExist  # importing raise error
from .models import Account  # importing account object


# main page
def index(request):
    return render(request, 'index.html')


# login page
def login_form(request):
    if not request.user.is_authenticated:  # if not authenticated render login, else go to menu
        return render(request, 'account/login.html')
    else:
        return redirect('bank:menu')


# login action
def login_action(request):
    # get the username and password then authenticate it
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:  # if authenticate is successful then login and redirect to menu
        login(request, user)
        return redirect('bank:menu')
    else:  # else show error
        messages.error(request, 'Sorry, wrong username / password or either account is not registered. ')
        return redirect('bank:login_form')


# logout action
def logout_action(request):
    logout(request)  # logout and redirect to main
    return redirect('bank:main')


# menu, need login to see this page
@login_required
def menu(request):
    name = request.user.get_full_name()  # show the full name
    return render(request, 'menu/menu.html', {'full_name': name})


# balance, need login to see this page
@login_required
def balance(request):
    acc = Account.objects.get(user_id=request.user.id)  # get the balance for the user that logged on
    return render(request, 'menu/balance.html', {'acc': acc})


# transfer action, need login to see this page
@login_required
def transfer(request):
    # Checking if user that receives the money exist.
    try:
        # Variables
        u_receive = request.POST['to']  # Username that will receive the money
        acc_sender = Account.objects.get(user_id=request.user.id)  # Getting the sender account object
        username_receiver = User.objects.get(username=u_receive)  # Getting the receiver object
        acc_receiver = Account.objects.get(user_id=username_receiver.id)  # Getting the account of receiver object
        amt = int(request.POST['amount'])  # Getting the amount of transferring

        # Checking if transfer to yourself. because if you're transferring to yourself there's money duplication bug.
        if u_receive != request.user.username:

            # Validates if amt less or equal than sender account balance.
            if amt <= acc_sender.balance and amt >= 10000:
                acc_sender.balance -= amt  # Subtracting your balance with the amount of amt
                acc_receiver.balance += amt  # Adding balance with the amount of amt
                acc_sender.save()  # Saving balance that has been subtracted to DB.
                acc_receiver.save()  # Saving balance that has been added to DB.
                messages.success(request, 'You have transferred Rp. {} to {}. You now only have Rp. {}'.format(
                    amt, u_receive, acc_sender.balance))
                return redirect('bank:transfer_form')
            else:
                messages.error(request,
                               'You don\'t have that much amount of balance or trying to transfer below the minimum amount. You only have Rp. {}'.format(
                                   acc_sender.balance))
                return redirect('bank:transfer_form')
        else:
            messages.error(request, 'You can\'t transfer to yourself!')
            return redirect('bank:transfer_form')
    except ObjectDoesNotExist:
        messages.error(request,
                       'You can\'t transfer to \'{}\' because that user doesn\'t exist.'.format(request.POST['to']))
        return redirect('bank:transfer_form')


# transfer page, need to be logged on
@login_required
def transfer_form(request):
    return render(request, 'menu/transfer.html')

bank/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Pacifico" rel="stylesheet">
    <title>ibank - {% block title %}{% endblock %}</title>
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class=" wrapper80 navbar-brand"><h1><a href="{% url 'bank:main' %}">ibank</a></h1></div>
    </div>
    <div class="wrapper80 content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        <div class="wrapper80">
        <p>&copy; ibank 2017</p>
        </div>
    </div>
</body>
</html>

bank/templates/index.html
{% extends 'base.html' %}
{% block title %}Main{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-3">Welcome to ibank.</h1>
        <p class="lead">Experience a new way in banking.</p>
        <p class="lead">Anywhere, anytime.</p>
        <hr class="my-4">
        <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url 'bank:login_form' %}">Login</a>
        </p>
    </div>
{% endblock %}

bank/templates/menu/balance.html
{% extends '../base.html' %}

{% block title %}Account{% endblock %}
{% block content %}
    <h2>Balance</h2>
    <a class="btn btn-primary btn-md" href="{% url 'bank:menu' %}">← Back to menu</a>
    <table class="table">
        <tr>
            <th id="your_balance">
               Your Balance:
            </th>
            <th>
                Rp. {{ acc.balance }}
            </th>
        </tr>
    </table>
{% endblock %}

bank/templates/menu/menu.html
{% extends '../base.html' %}

{% block title %}Account{% endblock %}
{% block content %}
    <h2>Hi, {{ full_name }}</h2>
    <h3>Welcome to ibank!</h3>
    <hr class="my-lg-4"/>
    <h4>Menu:</h4>
    <div class="list-group">
        <a class="list-group-item list-group-item-action btn btn-outline-success" href="{% url 'bank:balance' %}">Account Balance</a>
        <a class="list-group-item list-group-item-action btn btn-outline-success" href="{% url 'bank:transfer_form' %}">Transfer</a>
        <a class="btn btn-danger btn-block btn-lg" href="{% url 'bank:logout' %}">Logout</a>
    </div>
{% endblock %}

bank/templates/menu/transfer.html
{% extends '../base.html' %}

{% block title %}Account{% endblock %}
{% block content %}
    <h2>Transfer</h2>
    <a class="btn btn-primary btn-md" href="{% url 'bank:menu' %}">← Back to menu</a>
    <form action="{% url 'bank:transfer' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Account receiver username:</label>
            <input id="username" class="form-control" type="text" placeholder="Receiver's username" name="to" required>
        </div>
        <div class="form-group">
            <label for="amount">Amount:</label>
            <input id="amount" class="form-control" type="number" placeholder="Amount" name="amount" required>
            <small id="amountHelp" class="form-text text-muted">The minimum amount of transfer is Rp. 10000.</small>
        </div>
        <input class="btn btn-primary col-2" type="submit" value="Transfer">
    </form>
    {% if messages %}
        {% for message in messages %}
            <div class="{% if message.tags == "error" %}alert alert-danger{% elif message.tags == "success" %}alert alert-success{% endif %}">
                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}><strong>{{ message.tags }}! </strong>{{ message }}</p>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}